apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: script
spec:
  taskRef:
    name: script
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: maven
spec:
  taskRef:
    name: maven
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: maven-with-params
spec:
  taskRef:
    name: maven-with-params
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: maven-with-user-defined-params
spec:
  taskRef:
    name: maven-with-params
  params:
    - name: goal
      value: package
---
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: git-clone
spec:
  taskRef:
    name: git-clone
  params:
    - name: url
      value: https://github.com/kul-samples/java_sample_webapp
  workspaces:
    - name: output
      persistentVolumeClaim:
        claimName: workspaces
  podTemplate:
    nodeSelector:
      kubernetes.io/hostname: app-node-2