apiVersion: v1
kind: PersistentVolume
metadata:
  name: workspaces
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual
  volumeMode: Filesystem
  hostPath:
    path: "/tmp/workspaces"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workspaces
spec:
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: manual