apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: mvn-build
spec:
  description: |
    This is a Tekton Pipeline for create a Java Application Package (war, ear, jar).
  params:
    - name: repository
      type: string
      description: Git Repo to be cloned and build
    - name: revision
      type: string
      description: branch to clone for build
    - name: IMAGE
    - name: goal
      type: string
      description: Image TAG to be created
  workspaces:
    - name: source-code
    - name: git-credentials
    - name: dockerconfig
  tasks:
    - name: clone
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: source-code
        - name: ssh-directory
          workspace: git-credentials
      params:
        - name: url
          value: "$(params.repository)"
        - name: revision
          value: "$(params.revision)"
        - name: deleteExisting
          value: 'true'
    - name: build
      runAfter:
        - clone
      taskRef:
        name: maven-build
      workspaces:
        - name: source-code
          workspace: source-code
      params:
        - name: goal
          value: $(params.goal)
    - name: build-and-push-image
      runAfter:
        - build
      taskRef:
        name: kaniko
      workspaces:
        - name: source
          workspace: source-code
        - name: dockerconfig
          workspace: dockerconfig
      params:
        - name: IMAGE
          value: $(params.IMAGE)